services:
  - type: web
    name: parksons
    env: python
    region: frankfurt
    plan: free
    branch: main
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: SECRET_KEY
        value: 'django-insecure-m$y*je^!+vojmo30#-7#rfqy4ts!q!8iab#lf@kpi&q_)023am'
      - key: DEBUG
        value: "False"
