# Generated by Django 5.2.7 on 2025-10-02 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('code', models.AutoField(db_column='size_code', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='size_desc', max_length=40, null=True)),
                ('size_length', models.DecimalField(blank=True, db_column='sizelength', decimal_places=2, max_digits=10, null=True)),
                ('size_width', models.DecimalField(blank=True, db_column='sizewidth', decimal_places=2, max_digits=10, null=True)),
                ('unit_code', models.CharField(blank=True, max_length=4, null=True)),
                ('length_in_mm', models.DecimalField(blank=True, db_column='length', decimal_places=2, max_digits=10, null=True)),
                ('width_in_mm', models.DecimalField(blank=True, db_column='width', decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'db_table': 'sizes',
            },
        ),
    ]
