# Generated by Django 5.2.7 on 2025-10-03 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='active',
            field=models.CharField(blank=True, db_column='ACT', max_length=1, null=True),
        ),
    ]
