# Generated by Django 5.2.7 on 2025-10-05 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sizes', '0002_size_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='size',
            options={'ordering': ['code']},
        ),
        migrations.AlterField(
            model_name='size',
            name='active',
            field=models.BooleanField(db_column='ACT', default=True),
        ),
    ]
